/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedPlacementRouteImport } from './routes/_authenticated/placement'
import { Route as AuthenticatedPapersRouteImport } from './routes/_authenticated/papers'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedInternshipsRouteImport } from './routes/_authenticated/internships'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCodingRouteImport } from './routes/_authenticated/coding'
import { Route as AuthenticatedCgpaRouteImport } from './routes/_authenticated/cgpa'
import { Route as AuthenticatedResumesIdRouteImport } from './routes/_authenticated/resumes.$id'

const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementRoute = AuthenticatedPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPapersRoute = AuthenticatedPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternshipsRoute =
  AuthenticatedInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodingRoute = AuthenticatedCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCgpaRoute = AuthenticatedCgpaRouteImport.update({
  id: '/cgpa',
  path: '/cgpa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesIdRoute = AuthenticatedResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedResumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/cgpa': typeof AuthenticatedCgpaRoute
  '/coding': typeof AuthenticatedCodingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/placement': typeof AuthenticatedPlacementRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/resumes': typeof AuthenticatedResumesRouteWithChildren
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/cgpa': typeof AuthenticatedCgpaRoute
  '/coding': typeof AuthenticatedCodingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/placement': typeof AuthenticatedPlacementRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/resumes': typeof AuthenticatedResumesRouteWithChildren
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/_authenticated/cgpa': typeof AuthenticatedCgpaRoute
  '/_authenticated/coding': typeof AuthenticatedCodingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/internships': typeof AuthenticatedInternshipsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/papers': typeof AuthenticatedPapersRoute
  '/_authenticated/placement': typeof AuthenticatedPlacementRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRouteWithChildren
  '/_authenticated/resumes/$id': typeof AuthenticatedResumesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/resume-builder'
    | '/cgpa'
    | '/coding'
    | '/dashboard'
    | '/internships'
    | '/notes'
    | '/papers'
    | '/placement'
    | '/questions'
    | '/resume'
    | '/resumes'
    | '/resumes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/resume-builder'
    | '/cgpa'
    | '/coding'
    | '/dashboard'
    | '/internships'
    | '/notes'
    | '/papers'
    | '/placement'
    | '/questions'
    | '/resume'
    | '/resumes'
    | '/resumes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/resume-builder'
    | '/_authenticated/cgpa'
    | '/_authenticated/coding'
    | '/_authenticated/dashboard'
    | '/_authenticated/internships'
    | '/_authenticated/notes'
    | '/_authenticated/papers'
    | '/_authenticated/placement'
    | '/_authenticated/questions'
    | '/_authenticated/resume'
    | '/_authenticated/resumes'
    | '/_authenticated/resumes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement': {
      id: '/_authenticated/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof AuthenticatedPlacementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papers': {
      id: '/_authenticated/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AuthenticatedPapersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships': {
      id: '/_authenticated/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AuthenticatedInternshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding': {
      id: '/_authenticated/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof AuthenticatedCodingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cgpa': {
      id: '/_authenticated/cgpa'
      path: '/cgpa'
      fullPath: '/cgpa'
      preLoaderRoute: typeof AuthenticatedCgpaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/$id': {
      id: '/_authenticated/resumes/$id'
      path: '/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AuthenticatedResumesIdRouteImport
      parentRoute: typeof AuthenticatedResumesRoute
    }
  }
}

interface AuthenticatedResumesRouteChildren {
  AuthenticatedResumesIdRoute: typeof AuthenticatedResumesIdRoute
}

const AuthenticatedResumesRouteChildren: AuthenticatedResumesRouteChildren = {
  AuthenticatedResumesIdRoute: AuthenticatedResumesIdRoute,
}

const AuthenticatedResumesRouteWithChildren =
  AuthenticatedResumesRoute._addFileChildren(AuthenticatedResumesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCgpaRoute: typeof AuthenticatedCgpaRoute
  AuthenticatedCodingRoute: typeof AuthenticatedCodingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInternshipsRoute: typeof AuthenticatedInternshipsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPapersRoute: typeof AuthenticatedPapersRoute
  AuthenticatedPlacementRoute: typeof AuthenticatedPlacementRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCgpaRoute: AuthenticatedCgpaRoute,
  AuthenticatedCodingRoute: AuthenticatedCodingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInternshipsRoute: AuthenticatedInternshipsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPapersRoute: AuthenticatedPapersRoute,
  AuthenticatedPlacementRoute: AuthenticatedPlacementRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
